name: Extract Surge ZIP

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract files
        run: |
          unzip -o Surge.zip
          cp -a Surge/. .
          rm -rf Surge Surge.zip

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Import Surge configuration"
          git push
